version: '3'
services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Backend (Node.js) service
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - ./app/server/.env
    networks:
      - app-network

  # Frontend (React) service
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
